### ISSUE TITLE
Environment variables

### ISSUE THREAD

**Issue by mobreza** [rickyc19/Kubernetes-GGCE#1]
Hi there,

The names of variables for database connection (`SPRING_DATASOURCE_URL`, `SPRING_DATASOURCE_USERNAME` and `SPRING_DATASOURCE_PASSWORD`) will not get picked up by GGCE:

```yaml
        env:
        - name: SPRING_DATASOURCE_URL
        - name: SPRING_DATASOURCE_USERNAME
        - name: SPRING_DATASOURCE_PASSWORD
        - name: BASE_URL
        - name: FRONTEND_URL
```

https://ggce.genesys-pgr.org/docs/install/docker/ shows environment variables that GGCE recognizes:

```yaml
    environment:
      # Database connection
      - DB_URL=
      - DB_USERNAME=
      - DB_PASSWORD=
      # GGCE URLs
      - BASE_URL=
      - FRONTEND_URL=
```

Renaming `SPRING_DATASOURCE_URL` to `DB_URL`, `SPRING_DATASOURCE_USERNAME` to `DB_USERNAME` and `SPRING_DATASOURCE_PASSWORD` to `DB_PASSWORD` should help.

Matija
